[package]
name = "pretty-bytes-enum"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.182", features = ["serde_derive"], optional = true }

[features]
serde = ["dep:serde"]
